import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "./AuthProvider";
import dynamic from 'next/dynamic';
const Navbar = dynamic(() => import('./components/Navbar'), {ssr: false});
const Footer = dynamic(() => import('./components/Footer'), {ssr: false});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png'
  }
};


export default async function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body id='top'
          className={`${geistSans.variable} ${geistMono.variable} antialiased p-6`}
        >
          <Navbar />
          <hr className="border-gray-800" />
          {children}
          <Footer />
        </body>
      </html>
    </AuthProvider>
  );
}
